# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 500000

# # Replace the "❯" symbol in the prompt with "➜"
# [character] # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)"
# error_symbol = "[✗](bold red)"
# vimcmd_symbol = "[v](bold green)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

